[package]
name = "rusty_snake"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.24"
rand = "0.9.2"
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "food"
harness = false